### ISSUE TITLE
Missing community guideline for JOSS paper

### ISSUE THREAD

**Issue by Luthaf** [lxvm/AutoBZ.jl#42]
JOSS asks that all software published includes some guideline for community interaction, which I could not find in this repository or the documentation. 

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

A typical way to include these is to have a `CONTRIBUTING.md` file in the repository root, containing these guidelines. GitHub UI will then show these guidelines to first-time contributors/people opening issues. See also https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors about more ways to setup such guidelines on GitHub.

**Comment by lxvm** [comment]
Thank you for the review and I have added contributing guidelines for this repository in #45
